// Fixture data shaped like the real Supabase rows (src/lib/db-types.ts).
window.CJ_DATA = {
  coffees: [
    { id:"c1", name:"Ethiopia Guji Uraga", roaster:"Onyx Coffee Lab", country:"Ethiopia", region:"Guji",
      producer:"Uraga Washing Station", roast:"Light", rest:"2–3 weeks from roast",
      flavor:"Peach, bergamot, cane sugar", elevation:"1,950 masl", rating:8.6, ratingCount:4,
      processes:["Washed"], varietals:["Heirloom"], group:"active",
      bags:[{id:"b1",roast_date:"2026-07-18",status:"active",price:22.00,rested:15},{id:"b2",roast_date:"2026-06-02",status:"frozen",price:22.00,rested:0}] },
    { id:"c2", name:"Colombia El Paraíso", roaster:"Sey Coffee", country:"Colombia", region:"Cauca",
      producer:"Diego Bermúdez", roast:"Light", rest:"3 weeks from roast",
      flavor:"Lychee, rose, red apple", rating:9.1, ratingCount:2,
      processes:["Double anaerobic"], varietals:["Castillo"], group:"active",
      bags:[{id:"b3",roast_date:"2026-07-24",status:"resting",price:26.50,rested:6}] },
    { id:"c3", name:"Kenya Kirinyaga AA", roaster:"Tim Wendelboe", country:"Kenya", region:"Kirinyaga",
      roast:"Light", flavor:"Blackcurrant, tomato leaf", group:"storage", rating:8.0, ratingCount:1,
      processes:["Washed"], varietals:["SL28","SL34"], bags:[{id:"b4",roast_date:"2026-05-11",status:"frozen",price:24.00,rested:0}] },
    { id:"c4", name:"Brazil Fazenda Rainha", roaster:"Onyx Coffee Lab", country:"Brazil",
      roast:"Medium", flavor:"Cocoa, hazelnut", group:"history", rating:7.4, ratingCount:6,
      processes:["Natural"], varietals:["Yellow Bourbon"], bags:[{id:"b5",roast_date:"2026-03-02",status:"finished",price:18.00,rested:41}] },
  ],
  sessions: [
    { id:"s1", title:"Ethiopia Guji Uraga", type:"brewed_coffee", status:"active", date:"2026-08-02",
      method:"V60", brewer:"Hario V60 02", grinder:"1Zpresso K-Ultra", grind:"4.2", dose:18, water:300,
      anchor:"input", temp:93, bloom_g:50, bloom_t:"0:45", rested:15, total:"2:48",
      notes:"Bed looked even. Slightly faster drawdown than last time.", next:"Grind one click finer; hold 93 °C.",
      steps:[{time:"0:00",description:"Bloom, centre pour",weight:50,flow:null},
             {time:"0:45",description:"Spiral out to 150 g",weight:150,flow:3.2},
             {time:"1:30",description:"Final pour, keep bed flat",weight:300,flow:4.1},
             {time:"2:40",description:"Drawdown complete, swirl",weight:null,flow:null}],
      tasting:[{name:"Acidity",guidance:"Bright and lively vs soft and round",rating:4,notes:"Bergamot up front, no bite."},
               {name:"Sweetness",guidance:"Sugar-like intensity through the finish",rating:3,notes:""},
               {name:"Body",guidance:"Weight and texture in the mouth",rating:2,notes:"Tea-like."},
               {name:"Balance",guidance:"How the parts sit together",rating:4,notes:""}],
      overall:8.5 },
    { id:"s2", title:"Colombia El Paraíso", type:"brewed_coffee", status:"active", date:"2026-08-01", method:"Kalita Wave 155" },
    { id:"s3", title:"Cortado", type:"specialty_drink", status:"complete", date:"2026-07-30", overall:8.0 },
    { id:"s4", title:"Ethiopia Guji Uraga", type:"brewed_coffee", status:"complete", date:"2026-07-27", method:"V60", overall:8.0 },
    { id:"s5", title:"Iced shaken espresso", type:"specialty_drink", status:"complete", date:"2026-07-21", overall:7.5 },
  ],
  recipes: [
    { id:"r1", name:"Kalita 20 g standard", type:"brewed_coffee", method:"Kalita Wave 155", scope:"standard", favorite:true },
    { id:"r2", name:"Guji light-roast V60", type:"brewed_coffee", method:"V60", scope:"Ethiopia Guji Uraga", favorite:false },
    { id:"r3", name:"House cortado", type:"specialty_drink", method:null, scope:"standard", favorite:true },
    { id:"r4", name:"Iced shaken espresso", type:"specialty_drink", method:null, scope:"standard", favorite:false },
    { id:"r5", name:"Espresso 1:2 in 28 s", type:"brewed_coffee", method:"Espresso", scope:"standard", favorite:false },
  ],
  equipment: [
    { id:"e1", name:"Hario V60 02", category:"Brewer", sub:"Conical", workflow:true },
    { id:"e2", name:"1Zpresso K-Ultra", category:"Grinder", sub:"Conical", workflow:true },
    { id:"e3", name:"Kalita Wave 155", category:"Brewer", sub:"Flat-bottom", workflow:true },
    { id:"e4", name:"Acaia Pearl S", category:"Scale", sub:null, workflow:false },
    { id:"e7", name:"Timemore Sculptor 064S", category:"Grinder", sub:"Flat", workflow:true },
    { id:"e5", name:"Fellow Stagg EKG", category:"Kettle", sub:null, workflow:false },
    { id:"e6", name:"IMS precision basket 18 g", category:"Basket", sub:"Precision", workflow:true },
  ],
  ingredients: [
    { name:"Espresso (18 g in / 36 g out)", qty:36, unit:"g" },
    { name:"Whole milk, steamed", qty:120, unit:"g" },
  ],
  drinkSteps: [
    { description:"Pull an 18 g double into a warmed 5 oz cup." },
    { description:"Steam milk to 60 °C with a tight, glossy microfoam." },
    { description:"Pour from height, then drop in close for a small centred dot." },
  ],
};
