-- Phase 0: invite-code gate for registration.
-- Codes are generated by the owner (INSERT below). Sign-up validates + consumes a code
-- via the server-only service-role path. Clients never touch this table directly.

create extension if not exists pgcrypto;

create table if not exists public.invite_codes (
  id         uuid primary key default gen_random_uuid(),
  code       text unique not null,
  used_by    uuid references auth.users (id) on delete set null,
  used_at    timestamptz,
  created_at timestamptz not null default now()
);

-- RLS on, intentionally NO policies: with RLS enabled and no policy, anon/authenticated
-- clients get zero rows. Only the service-role key (which bypasses RLS) can read/write.
alter table public.invite_codes enable row level security;

-- Generate a starter invite code (change the value, or add more rows as needed):
-- insert into public.invite_codes (code) values ('LET-ME-IN-001');
